import assert from "node:assert/strict";
import { access, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";
import {
  installOperatorService,
  operatorServiceDefinition,
  operatorServiceStatus,
  shellCompletion,
  uninstallOperatorService,
  type OperatorCommandResult
} from "../src/operator-install.js";

test("completion generators cover the operator command surface without editing shell state", () => {
  for (const shell of ["bash", "zsh", "fish", "powershell"] as const) {
    const script = shellCompletion(shell);
    assert.match(script, /Generated by Cockroach Browser operator installer/);
    assert.match(script, /bootstrap/);
    assert.match(script, /service/);
    assert.match(script, /completion/);
    assert.match(script, /--confirm-local-owner/);
    assert.doesNotMatch(script, /sudo|Start-Process\s+-Verb\s+RunAs/i);
  }
});

test("Linux service installation is per-user, loopback-only, owner-confirmed, and reversible", async () => {
  const home = await mkdtemp(join(tmpdir(), "cockroach-browser-operator-"));
  const calls: Array<{ command: string; args: readonly string[] }> = [];
  const base = {
    platform: "linux" as const,
    home,
    root: join(home, ".cockroach-browser"),
    nodePath: join(home, "bin", "node"),
    cliPath: join(home, "lib", "cockroach-browser", "cli.js"),
    runner: async (command: string, args: readonly string[]): Promise<OperatorCommandResult> => {
      calls.push({ command, args: [...args] });
      return { command, args: [...args], stdout: "", stderr: "" };
    }
  };

  try {
    await mkdir(dirname(base.nodePath), { recursive: true });
    await mkdir(dirname(base.cliPath), { recursive: true });
    await writeFile(base.nodePath, "", "utf8");
    await writeFile(base.cliPath, "", "utf8");

    await assert.rejects(
      () => installOperatorService(base),
      /--confirm-local-owner/
    );

    const installed = await installOperatorService({
      ...base,
      confirmLocalOwner: true
    });
    assert.equal(installed.installed, true);
    assert.equal(installed.active, true);
    assert.equal(installed.kind, "systemd-user");
    const unit = await readFile(installed.path, "utf8");
    assert.match(unit, /ExecStart=.*127\.0\.0\.1/);
    assert.match(unit, /NoNewPrivileges=true/);
    assert.match(unit, /ProtectSystem=strict/);
    assert.doesNotMatch(unit, /0\.0\.0\.0|--allow-raw-actions|--allow-session-host-config|sudo/i);
    assert.deepEqual(
      calls.map((call) => [call.command, ...call.args]),
      [
        ["systemctl", "--user", "daemon-reload"],
        ["systemctl", "--user", "enable", "--now", "cockroach-browser.service"]
      ]
    );
    assert.equal((await operatorServiceStatus(base)).installed, true);

    calls.length = 0;
    const removed = await uninstallOperatorService({
      ...base,
      confirmLocalOwner: true
    });
    assert.equal(removed.installed, false);
    assert.equal(removed.active, false);
    assert.deepEqual(
      calls.map((call) => [call.command, ...call.args]),
      [
        ["systemctl", "--user", "disable", "--now", "cockroach-browser.service"],
        ["systemctl", "--user", "daemon-reload"]
      ]
    );
    await assert.rejects(() => access(installed.path), /ENOENT/);
  } finally {
    await rm(home, { recursive: true, force: true });
  }
});

test("Windows and macOS definitions remain in owner startup locations and never elevate", async () => {
  const home = await mkdtemp(join(tmpdir(), "cockroach-browser-platforms-"));
  try {
    const windows = operatorServiceDefinition({
      platform: "win32",
      home,
      appData: join(home, "AppData", "Roaming"),
      root: join(home, ".cockroach-browser"),
      nodePath: join(home, "node.exe"),
      cliPath: join(home, "cli.js")
    });
    assert.equal(windows.kind, "windows-startup");
    assert.match(windows.path, /Startup[\\/]cockroach-browser\.cmd$/);
    assert.match(windows.content, /127\.0\.0\.1/);
    assert.doesNotMatch(windows.content, /RunAs|0\.0\.0\.0|allow-raw-actions/i);

    const mac = operatorServiceDefinition({
      platform: "darwin",
      home,
      root: join(home, ".cockroach-browser"),
      nodePath: join(home, "bin", "node"),
      cliPath: join(home, "lib", "cli.js"),
      uid: 501
    });
    assert.equal(mac.kind, "launch-agent");
    assert.match(mac.path, /Library[\\/]LaunchAgents[\\/]io\.cockroach-browser\.daemon\.plist$/);
    assert.match(mac.content, /127\.0\.0\.1/);
    assert.deepEqual(mac.activation[0], {
      command: "launchctl",
      args: ["bootstrap", "gui/501", mac.path]
    });
    assert.doesNotMatch(mac.content, /0\.0\.0\.0|allow-raw-actions|sudo/i);
  } finally {
    await rm(home, { recursive: true, force: true });
  }
});

test("definition-only install does not start a process and refuses unrelated files", async () => {
  const home = await mkdtemp(join(tmpdir(), "cockroach-browser-owned-file-"));
  const options = {
    platform: "linux" as const,
    home,
    root: join(home, ".cockroach-browser"),
    nodePath: join(home, "node"),
    cliPath: join(home, "cli.js"),
    confirmLocalOwner: true,
    definitionOnly: true
  };
  try {
    await writeFile(options.nodePath, "", "utf8");
    await writeFile(options.cliPath, "", "utf8");
    const definition = operatorServiceDefinition(options);
    await mkdir(dirname(definition.path), { recursive: true });
    await writeFile(definition.path, "[Unit]\nDescription=Owner managed\n", "utf8");
    await assert.rejects(
      () => installOperatorService(options),
      /Refusing to overwrite an operator-managed file/
    );
    await assert.rejects(
      () => uninstallOperatorService(options),
      /Refusing to remove an operator-managed file/
    );
    assert.equal(await readFile(definition.path, "utf8"), "[Unit]\nDescription=Owner managed\n");
  } finally {
    await rm(home, { recursive: true, force: true });
  }
});
