export type CapabilityStatus = "available" | "adapter" | "planned";

export interface Capability {
  id: string;
  group: "sessions" | "interaction" | "evidence" | "audit" | "deployment" | "integration" | "security";
  title: string;
  summary: string;
  status: CapabilityStatus;
  surface: string;
}

export const CAPABILITIES: readonly Capability[] = Object.freeze([
  ["sessions.authorized", "sessions", "Authorized browser sessions", "Create sessions only from explicit user or host configuration.", "available", "runtime.createSession"],
  ["sessions.headless", "sessions", "Headless Chromium, Firefox, and WebKit", "Run any installed Playwright engine unattended with the same policy boundary.", "available", "engine and mode=headless"],
  ["sessions.lean", "sessions", "Lean headless asset profile", "Optionally block images, media, fonts, and service workers while preserving DOM, scripts, styles, forms, semantic snapshots, and governed actions.", "available", "performanceProfile=lean"],
  ["sessions.headed", "sessions", "Headed Chromium, Firefox, and WebKit", "Show an installed Playwright engine for review, login, and human handoff.", "available", "engine and mode=headed"],
  ["sessions.cdp", "sessions", "Attach over CDP", "Connect to a user-selected Chrome debugging endpoint.", "available", "cdpEndpoint"],
  ["sessions.executable", "sessions", "Custom browser executable", "Launch an explicitly supplied executable for the selected Chromium, Firefox, or WebKit engine.", "available", "engine and executablePath"],
  ["sessions.discovery", "sessions", "Cross-platform browser discovery", "Discover reviewed Chrome, Edge, Brave, and Chromium binaries on Windows, macOS, Linux, ARM64, and Raspberry Pi hosts.", "available", "browser discover and discoverBrowserExecutables"],
  ["sessions.providers", "sessions", "Explicit browser providers", "Select bundled, system, custom executable, or CDP providers without ambient profile discovery.", "available", "browserProvider"],
  ["sessions.raw_playwright", "sessions", "Complete raw Playwright API", "Re-export the installed Playwright browser, context, page, frame, locator, handle, worker, event, network, tracing, emulation, and protocol contracts without wrapping away upstream methods.", "available", "cockroach-browser/automation"],
  ["sessions.raw_puppeteer", "sessions", "Complete raw Puppeteer Core API", "Re-export the installed Puppeteer Core package, including browser, page, frame, target, handle, worker, CDP, coverage, tracing, emulation, and screencast contracts.", "available", "cockroach-browser/puppeteer"],
  ["sessions.raw_cdp", "sessions", "Raw Chrome DevTools Protocol sessions", "Connect to explicit CDP endpoints or create an unrestricted CDP session for an operator-owned Playwright page or frame.", "available", "cockroach-browser/cdp"],
  ["sessions.raw_bidi", "sessions", "Raw WebDriver BiDi sessions", "Send bounded arbitrary WebDriver BiDi commands, subscribe to events, and receive protocol events over operator-owned WebSocket endpoints.", "available", "cockroach-browser/bidi"],
  ["sessions.mobile_webdriver", "sessions", "Native mobile WebDriver and Appium transport", "Create W3C WebDriver sessions for operator-supplied Android, iOS, and Safari endpoints and issue both standard and vendor commands.", "available", "cockroach-browser/mobile"],
  ["sessions.extensions", "sessions", "Reviewed unpacked extensions", "Load explicit local extension directories in an isolated headed browser without downloading CRX files.", "available", "browserProvider.extensions"],
  ["sessions.profiles", "sessions", "Named isolated profiles", "Keep cookies and storage separated by an explicit profile name.", "available", "profile"],
  ["sessions.persistent_profiles", "sessions", "Runtime-owned persistent browser profiles", "Keep headed browser cookies, permissions, extensions, and storage across sessions in an explicit runtime-owned user-data directory, with single-writer locking and recoverable archival.", "available", "browserProvider.persistentProfile and /v1/profiles"],
  ["sessions.storage_import", "sessions", "Explicit storage-state import", "Import a user-selected encrypted storage-state file.", "available", "profile import"],
  ["sessions.storage_export", "sessions", "Explicit storage-state export", "Export a selected session for an authorized workflow.", "available", "profile export"],
  ["sessions.state_checkpoints", "sessions", "Encrypted state checkpoints", "Save, list, restore, and delete named encrypted cookie and same-origin storage checkpoints through host-owned passphrase references.", "available", "state.*"],
  ["sessions.clipboard", "sessions", "Policy-gated clipboard", "Read or write bounded clipboard text only when the host grants clipboard authority and resolves the exact secret reference.", "available", "clipboard.*"],
  ["sessions.proxy", "sessions", "User-supplied proxy", "Route one session through an explicitly configured proxy.", "available", "proxy"],
  ["sessions.locale", "sessions", "Locale and timezone", "Create deterministic locale and timezone contexts.", "available", "locale/timezoneId"],
  ["sessions.emulation", "sessions", "Device and network emulation", "Apply bounded viewport, media, offline, geolocation, permission, and non-secret header settings behind explicit emulation policy and approval.", "available", "emulation.set/clear"],
  ["sessions.raw_emulation", "sessions", "Complete upstream emulation controls", "Expose Playwright and Puppeteer device, clock, CPU, network, media, locale, timezone, geolocation, permission, vision, and browser-feature emulation contracts.", "available", "cockroach-browser/automation and cockroach-browser/puppeteer"],
  ["tabs.multiple", "interaction", "Tabs and popups", "Open, list, switch, and close bounded tabs.", "available", "tab.*"],
  ["tabs.lock", "interaction", "Exclusive tab locks", "Bind a tab to one owner and opaque lock-token reference for a finite lease before executing protected actions.", "available", "tab.lock/unlock/status"],
  ["page.navigate", "interaction", "Navigation", "Navigate, reload, go back, and go forward within allowed origins.", "available", "navigate/back/forward/reload"],
  ["page.refs", "interaction", "Snapshot-scoped page references", "Act on compact semantic references bound to the current observed page revision.", "available", "snapshot refs"],
  ["page.xpath", "interaction", "Explicit XPath targets", "Resolve a bounded XPath only when the exact action supplies it.", "available", "action.xpath"],
  ["page.snapshot", "interaction", "Semantic snapshots", "Return visible text and interactive elements with roles and names.", "available", "snapshot"],
  ["page.click", "interaction", "Click and double-click", "Activate referenced or selected elements after policy evaluation.", "available", "click/doubleClick"],
  ["page.form", "interaction", "Form interaction", "Fill, type, press, select, check, and uncheck.", "available", "fill/type/press/select/check"],
  ["page.hover_focus", "interaction", "Hover and focus", "Move focus without relying on viewport coordinates.", "available", "hover/focus"],
  ["page.scroll", "interaction", "Bounded scrolling", "Scroll by explicit deltas under action ceilings.", "available", "scroll"],
  ["page.mouse", "interaction", "Low-level mouse actions", "Move, press, release, or click only at explicit in-viewport coordinates.", "available", "mouse.*"],
  ["page.keyboard", "interaction", "Low-level keyboard actions", "Press, release, or insert bounded text through explicit actions.", "available", "keyboard.*"],
  ["page.drag", "interaction", "Drag and drop", "Drag between two authorized semantic references.", "available", "drag"],
  ["page.wait", "interaction", "Page-state waits", "Wait for selectors, text, or bounded timeouts.", "available", "wait"],
  ["page.shadow", "interaction", "Open Shadow DOM access", "Resolve selectors and references through open shadow roots.", "available", "snapshot"],
  ["page.iframe", "interaction", "Same-origin iframe access", "Include readable same-origin frames in snapshots.", "available", "snapshot"],
  ["page.frame_targeting", "interaction", "Same-origin frame targeting", "Target an exact index, name, or URL without entering cross-origin frames.", "available", "action.frame"],
  ["page.dialogs", "interaction", "Explicit dialog handling", "Dismiss dialogs by default and require policy plus approval before accepting one.", "available", "action.dialog"],
  ["page.history", "interaction", "Bounded browser history", "Inspect a sanitized, session-local record of observed page states under a finite retention ceiling.", "available", "history.inspect"],
  ["page.navigation_graph", "interaction", "Navigation graph", "Aggregate admitted page history into stable nodes and traversed edges for agent planning and review.", "available", "session graph and /navigation-graph"],
  ["page.javascript", "interaction", "Policy-gated JavaScript", "Evaluate JavaScript only when the session policy and approval allow it.", "available", "evaluate"],
  ["page.query", "interaction", "Bounded element inspection", "Inspect text, HTML, attributes, boxes, form state, visibility, enabled state, and counts for an explicit target.", "available", "query.inspect"],
  ["page.batch", "interaction", "Ordered action batches", "Run up to 100 exact policy-evaluated actions with stop-on-error or continue semantics and an individual receipt for every attempted step.", "available", "/actions/batch"],
  ["page.upload", "interaction", "File upload", "Upload explicit paths under byte and policy limits.", "available", "upload"],
  ["page.download", "interaction", "Controlled downloads", "Capture downloads into the evidence directory under byte limits.", "available", "download"],
  ["page.raw_handles", "interaction", "JSHandle and ElementHandle APIs", "Expose complete upstream JavaScript and element handle lifecycles, evaluation, property access, disposal, and element operations.", "available", "cockroach-browser/automation and cockroach-browser/puppeteer"],
  ["page.raw_events", "interaction", "Browser, context, page, target, worker, and frame events", "Expose complete upstream event emitters and typed event payloads for unrestricted operator automation.", "available", "cockroach-browser/automation and cockroach-browser/puppeteer"],
  ["page.raw_locators", "interaction", "Full locators and web assertions", "Expose Playwright locator composition, role and text queries, actionability, retries, and web-first assertions.", "available", "cockroach-browser/automation and cockroach-browser/test"],
  ["page.test_runner", "interaction", "Playwright Test runner", "Expose fixtures, projects, parallelism, retries, reporters, snapshots, test assertions, and multi-engine projects.", "available", "cockroach-browser/test and cockroach-browser-test"],
  ["page.codegen", "interaction", "Cross-language test generation", "Launch Playwright code generation for JavaScript, TypeScript, Python, Java, and C# targets.", "available", "cockroach-browser-codegen"],
  ["page.raw_network", "interaction", "General request and response rewriting", "Expose request continuation, method/header/body mutation, route fetch, abort, fulfill, response replacement, and context-level routing.", "available", "cockroach-browser/automation and cockroach-browser/puppeteer"],
  ["page.websocket", "interaction", "WebSocket inspection and routing", "Expose Playwright WebSocket events, frame inspection, message mocking, forwarding, mutation, and close handling.", "available", "cockroach-browser/automation"],
  ["evidence.screenshot", "evidence", "Screenshots", "Capture PNG or JPEG evidence with source metadata.", "available", "screenshot"],
  ["evidence.paired", "evidence", "Paired visual and semantic capture", "Capture a screenshot and semantic snapshot as one evidence set, optionally rejecting page drift and including reference bounds.", "available", "capture.paired and browser_capture"],
  ["evidence.annotations", "evidence", "Temporary page annotations", "Overlay bounded semantic-reference labels for review, then remove them without changing application state.", "available", "annotate.show/clear"],
  ["evidence.pdf", "evidence", "PDF capture", "Generate page PDFs in Chromium sessions.", "available", "pdf"],
  ["evidence.trace", "evidence", "Playwright traces", "Start and stop trace archives for authorized sessions.", "available", "trace.*"],
  ["evidence.har", "evidence", "HAR capture", "Record network archives when enabled at session creation.", "available", "recordHar"],
  ["evidence.har_replay", "evidence", "HAR replay and network mocking", "Replay HAR entries, update archives, abort missing requests, and combine archives with general route handlers.", "available", "BrowserContext.routeFromHAR and Page.routeFromHAR"],
  ["evidence.video", "evidence", "Session video", "Record browser video when enabled at session creation.", "available", "recordVideo"],
  ["evidence.console", "evidence", "Console records", "Capture bounded console messages with timestamps.", "available", "session evidence"],
  ["evidence.clear", "evidence", "Explicit runtime clearing", "Clear browser cache or retained console and network observations through policy-evaluated actions.", "available", "cache.clear/console.clear/network.clear"],
  ["evidence.network", "evidence", "Network records", "Capture bounded request and response metadata.", "available", "session evidence"],
  ["evidence.network_inspect", "evidence", "Network inspection", "Filter redacted request and response observations by method, status, and resource type under a finite record ceiling.", "available", "network.inspect and browser_network"],
  ["evidence.network_export", "evidence", "Network export", "Export the bounded redacted observation set as JSON, NDJSON, or HAR-compatible evidence.", "available", "network.export"],
  ["evidence.receipts", "evidence", "Hash-chained receipts", "Link action inputs, outputs, policy decisions, and evidence.", "available", "ActionReceipt"],
  ["evidence.extract", "evidence", "Text and HTML extraction", "Return bounded readable text or HTML fragments.", "available", "extract"],
  ["evidence.coverage", "evidence", "JavaScript and CSS coverage", "Expose Puppeteer coverage collection for JavaScript and stylesheets in Chromium sessions.", "available", "cockroach-browser/puppeteer Page.coverage"],
  ["evidence.heap", "evidence", "Heap snapshots and runtime object queries", "Expose raw CDP heap snapshots plus Puppeteer runtime object queries and handle inspection.", "available", "cockroach-browser/cdp and cockroach-browser/puppeteer"],
  ["evidence.screencast", "evidence", "Screencasting, metrics, and profiling", "Expose raw DevTools screencast, performance metrics, tracing, CPU profiling, and protocol diagnostics.", "available", "cockroach-browser/cdp and cockroach-browser/puppeteer"],
  ["audit.api_surface", "audit", "Generated upstream API inventory", "Generate and verify every public class and interface member exposed by the pinned Playwright and Puppeteer declarations.", "available", "docs/compatibility/browser-api-surface.json"],
  ["audit.accessibility", "audit", "Accessibility audit", "Inspect semantic names, labels, heading order, and obvious failures.", "available", "audit accessibility"],
  ["audit.performance", "audit", "Page performance observations", "Collect navigation timing, paint entries, transfer sizes, and resource summaries.", "available", "audit performance"],
  ["audit.resources", "audit", "Repeatable cross-engine resource benchmark", "Measure browser-tree RSS, CPU time, process count, coordinator memory, network transfer, evidence storage, and phase latency across balanced and lean profiles.", "available", "npm run benchmark:resources"],
  ["audit.assets", "audit", "Broken asset audit", "Report failed scripts, styles, images, and requests.", "available", "audit assets"],
  ["audit.console", "audit", "Console error audit", "Summarize browser errors and warnings.", "available", "audit console"],
  ["audit.security", "audit", "Page security observations", "Report mixed content and insecure form targets visible to the page runtime.", "available", "audit security"],
  ["audit.visual", "audit", "Visual comparison", "Compare screenshots and emit a diff plus mismatch percentage.", "available", "compare"],
  ["challenge.detect", "security", "Challenge detection", "Detect login, consent, CAPTCHA, and access challenges.", "available", "challenge"],
  ["challenge.handoff", "security", "Human challenge handoff", "Pause for a user or authorized resolver instead of bypassing controls.", "available", "challenge wait"],
  ["challenge.authorized_resolver", "security", "Authorized challenge resolver", "Request a host-owned operator workflow through a page-less callback, then independently verify the page before resuming.", "available", "challenge.resolve"],
  ["challenge.provider", "security", "Provider-authorized challenge service", "Request a declared provider challenge mode through the fleet adapter without silently widening engine, region, proxy, or session authority.", "adapter", "BrowserFleetProvider.challengeModes"],
  ["security.origins", "security", "Origin allowlists", "Fail closed when navigation leaves explicitly allowed origins.", "available", "allowedOrigins"],
  ["security.private_network", "security", "Private-network blocking", "Reject private and loopback destinations in the public browser adapter.", "available", "policy"],
  ["security.effects", "security", "Effect-level policy", "Separate read, write, execute, upload, download, and credential authority.", "available", "allowedEffects"],
  ["security.budgets", "security", "Finite budgets", "Clamp actions, tabs, time, browser-process RSS and CPU, upload, download, snapshot, and evidence size.", "available", "budget"],
  ["security.process_resources", "security", "Owned browser process-tree governor", "Sample aggregate RSS, cumulative CPU time, and process count for runtime-owned browsers; terminate periodically detected limit breaches and disclose unsupported external ownership.", "available", "session resources, CLI, dashboard, and Prometheus"],
  ["security.network_routes", "security", "Policy-bounded network routes", "Abort or statically fulfill exact-origin requests under per-rule and session byte ceilings.", "available", "network.route.*"],
  ["security.approvals", "security", "Exact action approvals", "Bind high-risk approval to the canonical action input.", "adapter", "MaqamApprovalProvider"],
  ["security.secrets", "security", "Secret references", "Resolve proxy and integration secrets through the host, never manifests.", "adapter", "SecretResolver"],
  ["deploy.cli", "deployment", "Command-line interface", "Manage authorized sessions and observations; direct actions require an explicit trusted-host opt-in.", "available", "cockroach-browser"],
  ["deploy.completions", "deployment", "Shell completions", "Generate auditable Bash, Zsh, Fish, or PowerShell completion scripts without modifying shell profiles.", "available", "completion bash|zsh|fish|powershell"],
  ["deploy.user_service", "deployment", "Per-user daemon autostart", "Install an owner-confirmed loopback daemon definition for Windows Startup, macOS LaunchAgents, or Linux systemd user services without privilege escalation.", "available", "service install|status|uninstall"],
  ["deploy.bootstrap", "deployment", "One-command three-engine bootstrap", "Verify Node, install Chromium, Firefox, and WebKit only when any engine is missing, initialize the local data root, and probe an authenticated ephemeral loopback daemon.", "available", "bootstrap"],
  ["deploy.sdk", "deployment", "TypeScript SDK", "Embed the runtime or call an authenticated daemon.", "available", "BrowserRuntime/BrowserClient"],
  ["deploy.sdk_python", "deployment", "Python SDK", "Call every daemon route through a dependency-free Python 3.10 client with typed convenience methods for sessions and actions.", "available", "sdks/python"],
  ["deploy.sdk_java", "deployment", "Java SDK", "Call every daemon route through a Java 11 HttpClient with session and action conveniences.", "available", "sdks/java"],
  ["deploy.sdk_dotnet", "deployment", ".NET and C# SDK", "Call every daemon route through a .NET 8 HttpClient with async session and action conveniences.", "available", "sdks/dotnet"],
  ["deploy.sdk_ruby", "deployment", "Ruby SDK", "Call every daemon route through a Ruby 3.1 standard-library client with session and action conveniences.", "available", "sdks/ruby"],
  ["deploy.sdk_go", "deployment", "Go SDK", "Call every daemon route through a Go 1.22 standard-library client with context cancellation and generic route access.", "available", "sdks/go"],
  ["deploy.http", "deployment", "Authenticated HTTP API", "Expose the runtime through a bearer-token localhost server.", "available", "serve"],
  ["deploy.openapi", "deployment", "OpenAPI discovery", "Publish an authenticated machine-readable route index for local SDK and operator tooling.", "available", "/v1/openapi.json"],
  ["deploy.metrics", "deployment", "Prometheus metrics", "Expose authenticated session, action, and failure counters for local operations.", "available", "/v1/metrics"],
  ["deploy.mcp", "deployment", "Observation-first MCP server", "Expose health, capabilities, sessions, snapshots, paired capture, network observations, audits, and canonical Maqam action proposals over stdio.", "available", "mcp"],
  ["deploy.docker", "deployment", "Three-engine Docker runtime", "Run installed Chromium, Firefox, and WebKit builds plus the authenticated daemon in a hardened container.", "available", "Dockerfile"],
  ["deploy.dashboard", "deployment", "Local dashboard", "Inspect sessions, evidence, challenges, and receipts.", "available", "dashboard"],
  ["deploy.remote", "deployment", "Authenticated remote workers", "Connect SDK clients to explicitly configured remote daemons.", "available", "BrowserClient"],
  ["deploy.worker_pool", "deployment", "Multi-worker orchestration", "Route sessions across healthy authenticated browser daemons by capacity, weight, and explicit tags.", "available", "BrowserWorkerPool"],
  ["deploy.local_fleet", "deployment", "Local multi-engine process fleet", "Allocate and connect bounded Chromium, Firefox, or WebKit browser-server leases with TTL and capacity enforcement.", "available", "LocalBrowserFleetProvider"],
  ["deploy.remote_fleet", "deployment", "Managed and self-hosted fleet adapter", "Connect an authenticated REST fleet that declares exact engines, regions, proxy classes, challenge modes, capacity, and TTLs.", "adapter", "HttpBrowserFleetProvider"],
  ["deploy.live_view", "deployment", "Provider live-session viewer", "Return a validated HTTPS live-view URL when the selected fleet provider supplies one.", "adapter", "FleetProviderSession.liveViewUrl"],
  ["deploy.managed_proxy", "deployment", "Residential, datacenter, static-IP, and custom proxy providers", "Request an exact declared proxy class and geography from a selected fleet provider; Cockroach Browser does not operate the proxy network.", "adapter", "FleetProxyRequest"],
  ["deploy.activity", "deployment", "Configurable activity stream", "Read bounded summary or detailed lifecycle activity through polling or server-sent events.", "available", "/v1/activity and /v1/activity/stream"],
  ["deploy.queue", "deployment", "Durable local jobs", "Queue bounded action plans with checkpoints and retries.", "available", "JobQueue"],
  ["deploy.health", "deployment", "Doctor and daemon health checks", "Verify the supported Node release, Chromium, Firefox, and WebKit installations, daemon authentication, evidence integrity, and active session count.", "available", "doctor and /v1/health"],
  ["integration.maqam", "integration", "Maqam governance", "Route high-risk browser actions through exact approval and receipts.", "adapter", "cockroach-browser/maqam"],
  ["integration.qarinah", "integration", "Qarinah memory", "Record cited browser outcomes without persisting hidden reasoning or secrets.", "adapter", "cockroach-browser/qarinah"],
  ["integration.crawler", "integration", "Cockroach Crawler handoff", "Hand breadth-first collection to the crawler while retaining browser evidence.", "adapter", "cockroach-browser/crawler"],
  ["integration.productloop", "integration", "ProductLoop capability snapshot", "Describe browser capabilities for a separately reviewed ProductLoop adapter without granting authority.", "adapter", "docs/productloop.md"],
  ["integration.webhooks", "integration", "Signed lifecycle webhooks", "Queue sanitized browser lifecycle events for bounded HMAC-signed HTTPS delivery.", "available", "SignedWebhookDispatcher"],
  ["integration.team_sync", "integration", "Team session control", "Persist session owners, viewer and operator grants, revocation generations, policy, and receipts without sharing raw profiles.", "available", "TeamSessionStore and /access"],
  ["integration.model_gateway", "integration", "Built-in model gateway", "Call an OpenAI-compatible model endpoint with bounded requests, tool definitions, structured tool calls, timeouts, and secret-provider support.", "available", "cockroach-browser/model-gateway"],
  ["integration.browser_agent", "integration", "Built-in browser planner loop", "Iterate semantic snapshots, policy-evaluated browser actions, receipts, and an explicit finish tool under a finite step ceiling.", "available", "cockroach-browser/agent"]
].map(([id, group, title, summary, status, surface]) => ({ id, group, title, summary, status, surface })) as Capability[]);

export function capabilities(status?: CapabilityStatus): Capability[] {
  return CAPABILITIES.filter((entry) => !status || entry.status === status).map((entry) => ({ ...entry }));
}
