import { execFile } from "node:child_process";
import { access, chmod, mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export type OperatorPlatform = "win32" | "darwin" | "linux";
export type CompletionShell = "bash" | "zsh" | "powershell";

export interface OperatorCommandResult {
  command: string;
  args: readonly string[];
  stdout: string;
  stderr: string;
}

export type OperatorCommandRunner = (
  command: string,
  args: readonly string[]
) => Promise<OperatorCommandResult>;

export interface OperatorInstallOptions {
  platform?: NodeJS.Platform;
  home?: string;
  appData?: string;
  root?: string;
  nodePath?: string;
  cliPath?: string;
  port?: number;
  uid?: number;
  confirmLocalOwner?: boolean;
  definitionOnly?: boolean;
  runner?: OperatorCommandRunner;
}

export interface OperatorServiceDefinition {
  platform: OperatorPlatform;
  kind: "windows-startup" | "launch-agent" | "systemd-user";
  path: string;
  root: string;
  command: readonly string[];
  content: string;
  activation: readonly OperatorActivationCommand[];
  deactivation: readonly OperatorActivationCommand[];
  startsAtNextLogin: boolean;
}

export interface OperatorActivationCommand {
  command: string;
  args: readonly string[];
}

export interface OperatorServiceResult {
  installed: boolean;
  active: boolean;
  definitionOnly: boolean;
  startsAtNextLogin: boolean;
  platform: OperatorPlatform;
  kind: OperatorServiceDefinition["kind"];
  path: string;
  root: string;
  command: readonly string[];
  activation: readonly OperatorCommandResult[];
}

const GENERATED_MARKER = "Generated by Cockroach Browser operator installer";
const SERVICE_NAME = "cockroach-browser";
const LAUNCH_AGENT_NAME = "io.cockroach-browser.daemon";
const COMMANDS = [
  "bootstrap",
  "setup",
  "doctor",
  "completion",
  "service",
  "serve",
  "mcp",
  "capabilities",
  "session",
  "snapshot",
  "audit",
  "act",
  "profile",
  "version",
  "help"
] as const;

export function shellCompletion(shell: CompletionShell): string {
  if (shell === "bash") return bashCompletion();
  if (shell === "zsh") return zshCompletion();
  if (shell === "powershell") return powershellCompletion();
  throw new Error(`Unsupported shell: ${String(shell)}. Use bash, zsh, or powershell.`);
}

export function operatorServiceDefinition(options: OperatorInstallOptions = {}): OperatorServiceDefinition {
  const platform = supportedPlatform(options.platform ?? process.platform);
  const home = resolve(options.home ?? homedir());
  const root = resolve(options.root ?? join(home, ".cockroach-browser"));
  assertInside(home, root, "The daemon root");
  const nodePath = resolve(options.nodePath ?? process.execPath);
  const cliPath = resolve(options.cliPath ?? fileURLToPath(new URL("./cli.js", import.meta.url)));
  const port = operatorPort(options.port);
  const command = Object.freeze([
    nodePath,
    cliPath,
    "serve",
    "--host",
    "127.0.0.1",
    "--port",
    String(port),
    "--root",
    root
  ]);

  if (platform === "win32") {
    const appData = resolve(options.appData ?? process.env.APPDATA ?? join(home, "AppData", "Roaming"));
    assertInside(home, appData, "APPDATA");
    const path = resolve(
      appData,
      "Microsoft",
      "Windows",
      "Start Menu",
      "Programs",
      "Startup",
      `${SERVICE_NAME}.cmd`
    );
    assertInside(appData, path, "The Startup definition");
    const commandLine = command.map(quoteWindowsCommandArgument).join(" ");
    return {
      platform,
      kind: "windows-startup",
      path,
      root,
      command,
      content:
        `@echo off\r\n` +
        `REM ${GENERATED_MARKER}. Do not add remote binding or raw-action flags here.\r\n` +
        `${commandLine} >> ${quoteWindowsCommandArgument(join(root, "daemon.log"))} 2>&1\r\n`,
      activation: [],
      deactivation: [],
      startsAtNextLogin: true
    };
  }

  if (platform === "darwin") {
    const path = resolve(home, "Library", "LaunchAgents", `${LAUNCH_AGENT_NAME}.plist`);
    assertInside(home, path, "The LaunchAgent definition");
    const uid = options.uid ?? (typeof process.getuid === "function" ? process.getuid() : undefined);
    if (uid === undefined) throw new Error("Cannot determine the current macOS user ID.");
    return {
      platform,
      kind: "launch-agent",
      path,
      root,
      command,
      content: launchAgent(command, root),
      activation: [
        { command: "launchctl", args: ["bootstrap", `gui/${uid}`, path] }
      ],
      deactivation: [
        { command: "launchctl", args: ["bootout", `gui/${uid}/${LAUNCH_AGENT_NAME}`] }
      ],
      startsAtNextLogin: true
    };
  }

  const path = resolve(home, ".config", "systemd", "user", `${SERVICE_NAME}.service`);
  assertInside(home, path, "The systemd user definition");
  return {
    platform,
    kind: "systemd-user",
    path,
    root,
    command,
    content: systemdUnit(command, root),
    activation: [
      { command: "systemctl", args: ["--user", "daemon-reload"] },
      { command: "systemctl", args: ["--user", "enable", "--now", `${SERVICE_NAME}.service`] }
    ],
    deactivation: [
      { command: "systemctl", args: ["--user", "disable", "--now", `${SERVICE_NAME}.service`] },
      { command: "systemctl", args: ["--user", "daemon-reload"] }
    ],
    startsAtNextLogin: true
  };
}

export async function installOperatorService(
  options: OperatorInstallOptions = {}
): Promise<OperatorServiceResult> {
  assertLocalOwnerConfirmation(options);
  const definition = operatorServiceDefinition(options);
  await assertOperatorExecutables(definition);
  await mkdir(definition.root, { recursive: true });
  await mkdir(dirname(definition.path), { recursive: true });
  await writeOwnedDefinition(definition);
  const activation = options.definitionOnly
    ? []
    : await runCommands(definition.activation, options.runner ?? runOperatorCommand);
  return {
    installed: true,
    active: !options.definitionOnly && definition.activation.length > 0,
    definitionOnly: Boolean(options.definitionOnly),
    startsAtNextLogin: definition.startsAtNextLogin,
    platform: definition.platform,
    kind: definition.kind,
    path: definition.path,
    root: definition.root,
    command: definition.command,
    activation
  };
}

export async function uninstallOperatorService(
  options: OperatorInstallOptions = {}
): Promise<OperatorServiceResult> {
  assertLocalOwnerConfirmation(options);
  const definition = operatorServiceDefinition(options);
  const installed = await ownsDefinition(definition.path);
  const activation = options.definitionOnly || !installed
    ? []
    : await runCommands(definition.deactivation, options.runner ?? runOperatorCommand, true);
  if (installed) await unlink(definition.path);
  return {
    installed: false,
    active: false,
    definitionOnly: Boolean(options.definitionOnly),
    startsAtNextLogin: definition.startsAtNextLogin,
    platform: definition.platform,
    kind: definition.kind,
    path: definition.path,
    root: definition.root,
    command: definition.command,
    activation
  };
}

export async function operatorServiceStatus(
  options: Omit<OperatorInstallOptions, "confirmLocalOwner" | "runner"> = {}
): Promise<Omit<OperatorServiceResult, "activation">> {
  const definition = operatorServiceDefinition(options);
  const installed = await ownsDefinition(definition.path);
  return {
    installed,
    active: false,
    definitionOnly: false,
    startsAtNextLogin: definition.startsAtNextLogin,
    platform: definition.platform,
    kind: definition.kind,
    path: definition.path,
    root: definition.root,
    command: definition.command
  };
}

export async function runOperatorCommand(
  command: string,
  args: readonly string[]
): Promise<OperatorCommandResult> {
  return new Promise<OperatorCommandResult>((accept, reject) => {
    execFile(command, [...args], { encoding: "utf8", windowsHide: true }, (error, stdout, stderr) => {
      if (error) {
        reject(new Error(
          `${command} ${args.join(" ")} failed: ${stderr.trim() || error.message}`
        ));
        return;
      }
      accept({ command, args: [...args], stdout, stderr });
    });
  });
}

async function runCommands(
  commands: readonly OperatorActivationCommand[],
  runner: OperatorCommandRunner,
  tolerateFailure = false
): Promise<OperatorCommandResult[]> {
  const results: OperatorCommandResult[] = [];
  for (const item of commands) {
    try {
      results.push(await runner(item.command, item.args));
    } catch (error) {
      if (!tolerateFailure) throw error;
      results.push({
        command: item.command,
        args: [...item.args],
        stdout: "",
        stderr: error instanceof Error ? error.message : String(error)
      });
    }
  }
  return results;
}

async function writeOwnedDefinition(definition: OperatorServiceDefinition): Promise<void> {
  try {
    const current = await readFile(definition.path, "utf8");
    if (!current.includes(GENERATED_MARKER)) {
      throw new Error(`Refusing to overwrite an operator-managed file: ${definition.path}`);
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  await writeFile(definition.path, definition.content, {
    encoding: "utf8",
    ...(definition.platform === "win32" ? {} : { mode: 0o600 })
  });
  if (definition.platform !== "win32") await chmod(definition.path, 0o600);
}

async function assertOperatorExecutables(definition: OperatorServiceDefinition): Promise<void> {
  for (const path of definition.command.slice(0, 2)) {
    try {
      await access(path);
    } catch {
      throw new Error(`The daemon executable does not exist: ${path}. Build or reinstall Cockroach Browser first.`);
    }
  }
}

async function ownsDefinition(path: string): Promise<boolean> {
  try {
    const current = await readFile(path, "utf8");
    if (!current.includes(GENERATED_MARKER)) {
      throw new Error(`Refusing to remove an operator-managed file: ${path}`);
    }
    return true;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return false;
    throw error;
  }
}

function supportedPlatform(platform: NodeJS.Platform): OperatorPlatform {
  if (platform === "win32" || platform === "darwin" || platform === "linux") return platform;
  throw new Error(`Daemon autostart is supported on Windows, macOS, and Linux; received ${platform}.`);
}

function operatorPort(value = 43110): number {
  if (!Number.isSafeInteger(value) || value < 1 || value > 65_535) {
    throw new Error("The daemon port must be an integer from 1 through 65535.");
  }
  return value;
}

function assertLocalOwnerConfirmation(options: OperatorInstallOptions): void {
  if (!options.confirmLocalOwner) {
    throw new Error(
      "Service changes require --confirm-local-owner. This confirms you own the current OS account and accept a loopback daemon starting at login."
    );
  }
}

function assertInside(parent: string, child: string, label: string): void {
  const relation = relative(resolve(parent), resolve(child));
  if (!relation || relation.startsWith("..") || relation.includes(`..${process.platform === "win32" ? "\\" : "/"}`)) {
    if (!relation) {
      throw new Error(`${label} must be a child path, not the user-home directory itself.`);
    }
    throw new Error(`${label} must stay inside the current user's home directory.`);
  }
}

function quoteWindowsCommandArgument(value: string): string {
  if (/[\r\n"]/.test(value)) throw new Error("Windows service paths cannot contain quotes or newlines.");
  return `"${value.replaceAll("%", "%%")}"`;
}

function systemdUnit(command: readonly string[], root: string): string {
  const quoted = command.map(systemdQuote).join(" ");
  return `# ${GENERATED_MARKER}. Do not add remote binding or raw-action flags here.
[Unit]
Description=Cockroach Browser local owner daemon
After=network.target

[Service]
Type=simple
ExecStart=${quoted}
Restart=on-failure
RestartSec=3
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=read-only
ReadWritePaths=${systemdQuote(root)}
UMask=0077

[Install]
WantedBy=default.target
`;
}

function systemdQuote(value: string): string {
  if (/[\r\n]/.test(value)) throw new Error("systemd service paths cannot contain newlines.");
  return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"').replaceAll("%", "%%")}"`;
}

function launchAgent(command: readonly string[], root: string): string {
  const args = command.map((entry) => `    <string>${xmlEscape(entry)}</string>`).join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- ${GENERATED_MARKER}. Do not add remote binding or raw-action flags here. -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LAUNCH_AGENT_NAME}</string>
  <key>ProgramArguments</key>
  <array>
${args}
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict><key>SuccessfulExit</key><false/></dict>
  <key>StandardOutPath</key>
  <string>${xmlEscape(join(root, "daemon.log"))}</string>
  <key>StandardErrorPath</key>
  <string>${xmlEscape(join(root, "daemon-error.log"))}</string>
  <key>ProcessType</key>
  <string>Background</string>
</dict>
</plist>
`;
}

function xmlEscape(value: string): string {
  if (/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/.test(value)) {
    throw new Error("LaunchAgent paths cannot contain XML control characters.");
  }
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

function bashCompletion(): string {
  const commands = COMMANDS.join(" ");
  return `# ${GENERATED_MARKER}
_cockroach_browser() {
  local current previous
  COMPREPLY=()
  current="\${COMP_WORDS[COMP_CWORD]}"
  previous="\${COMP_WORDS[COMP_CWORD-1]}"
  if [[ \${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "${commands}" -- "\${current}") )
    return
  fi
  case "\${COMP_WORDS[1]}" in
    completion) COMPREPLY=( $(compgen -W "bash zsh powershell" -- "\${current}") ) ;;
    service) COMPREPLY=( $(compgen -W "install uninstall status --confirm-local-owner --definition-only --root --port" -- "\${current}") ) ;;
    session) COMPREPLY=( $(compgen -W "create list get close" -- "\${current}") ) ;;
    profile) COMPREPLY=( $(compgen -W "list import export" -- "\${current}") ) ;;
    capabilities) COMPREPLY=( $(compgen -W "--status available adapter planned" -- "\${current}") ) ;;
    *) COMPREPLY=( $(compgen -W "--help --root --token-file" -- "\${current}") ) ;;
  esac
}
complete -F _cockroach_browser cockroach-browser
`;
}

function zshCompletion(): string {
  return `#compdef cockroach-browser
# ${GENERATED_MARKER}
_cockroach_browser() {
  local -a commands
  commands=(
${COMMANDS.map((command) => `    '${command}:${completionDescription(command)}'`).join("\n")}
  )
  if (( CURRENT == 2 )); then
    _describe 'command' commands
    return
  fi
  case "$words[2]" in
    completion) _values 'shell' bash zsh powershell ;;
    service) _values 'operation' install uninstall status '--confirm-local-owner[confirm local account ownership]' '--definition-only[write definition without activation]' '--root[daemon data root]' '--port[loopback port]' ;;
    session) _values 'operation' create list get close ;;
    profile) _values 'operation' list import export ;;
    capabilities) _values 'filter' '--status[available, adapter, or planned]' ;;
    *) _arguments '*:argument:_files' ;;
  esac
}
_cockroach_browser "$@"
`;
}

function powershellCompletion(): string {
  const commands = COMMANDS.map((entry) => `'${entry}'`).join(", ");
  return `# ${GENERATED_MARKER}
Register-ArgumentCompleter -Native -CommandName cockroach-browser -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)
  $words = @($commandAst.CommandElements | ForEach-Object { $_.Extent.Text })
  $candidates = @(${commands})
  if ($words.Count -ge 2) {
    switch ($words[1]) {
      'completion' { $candidates = @('bash', 'zsh', 'powershell') }
      'service' { $candidates = @('install', 'uninstall', 'status', '--confirm-local-owner', '--definition-only', '--root', '--port') }
      'session' { $candidates = @('create', 'list', 'get', 'close') }
      'profile' { $candidates = @('list', 'import', 'export') }
      'capabilities' { $candidates = @('--status', 'available', 'adapter', 'planned') }
      default { $candidates = @('--help', '--root', '--token-file') }
    }
  }
  $candidates |
    Where-Object { $_ -like "$wordToComplete*" } |
    ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
}
`;
}

function completionDescription(command: typeof COMMANDS[number]): string {
  const descriptions: Record<typeof COMMANDS[number], string> = {
    bootstrap: "Initialize, install Chromium when needed, and probe the localhost daemon",
    setup: "Alias for bootstrap",
    doctor: "Inspect local readiness",
    completion: "Generate a shell completion script",
    service: "Manage a per-user loopback daemon definition",
    serve: "Run the authenticated browser daemon",
    mcp: "Run the observation-first MCP server",
    capabilities: "Print the capability registry",
    session: "Manage browser sessions",
    snapshot: "Capture semantic page state",
    audit: "Run page audits",
    act: "Dispatch a trusted-host action",
    profile: "Manage explicit encrypted profile files",
    version: "Print the package version",
    help: "Show command help"
  };
  return descriptions[command];
}

export async function operatorDefinitionExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}
